# CONFIGURATION
pdf_files: Drive:\Location\Of\PDF\Files\*.pdf # Location of PDF files. Keep "*.pdf" after adding the path
unprocessed_folder: Drive:\Location\Of\Files\To\Be\Processed\ # Location where PDF files that need to be extracted go
processed_folder: Dive:\Location\Where\Processed\Files\Should\Be\Moved\To\ # Location where extracted PDF files go
folder_names: # Path to folders where exported data goes. Ensure they are in the same order as they appear in the page numbers
    - Drive:\Path\To\Folder\One
    - Drive:\Path\To\Folder\Two
    - Drive:\Path\To\Folder\Three
pdf_pages_to_extract: page,numbers,of,tables,to,be,extracted,separated,by,commas # Page numbers of the document itself, NOT page numbers of the pages (i.e. NOT the number at the bottom of the page)
flavor: stream # The type of PDF data extraction to utilize. Default: stream. lattice: Used where the data tables are formatted in a grid. stream: used when data tables aren't formatted and need to be inferred

# OPTIONAL CONFIGURATION
optional_cleaning: 0 # 1 = on, 0 = off. Turn on optional cleaning. By default (without below options), removes columns where there are only 'NaN' values
clean_start: Column Name # Text where you would want column headers to start. If extracted PDF has space or additional unneeded text before data starts, use this option to remove it
clean_end: Value # Value to end the data on.
filter_column: Column Name # Column that needs filtering
filter_values: # Values to filter out of data. Ex) Filter 'Column A' where value equals 'Value(s) Below'. Add more by more adding '-'s. 
    - Filter Value One
    - Filter Value Two