pdf_files: 'I:\\99 Other Projects\\CO Monthly Summary\\MMRs\\Unprocessed\\*.pdf'
unprocessed_folder: 'I:\\99 Other Projects\\CO Monthly Summary\\MMRs\\Unprocessed\\'
processed_folder: 'I:\\99 Other Projects\\CO Monthly Summary\\MMRs\\Processed\\'
export_folder: 'I:\\99 Other Projects\\CO Monthly Summary\\Data\\'
folder_names:
    - PEP
    - Case Orders
    - Current Sup Paid Percent
    - Arrears Cases with Payment
    - Monthly Arrears Cases
    - Monthly Collections
    - Percent of Arrears Paid
    - FTE Counts
pdf_pages_to_extract: '4,5,9,13,14,17,26,29'